FROM holishing/imagedreambbs:runenv-f4ad744
MAINTAINER holishing

RUN yum update -y \
    && yum clean all \
    && yum install --nogpgcheck -y \
	cronie

WORKDIR /home/bbs
USER bbs
ENV HOME=/home/bbs
COPY file/crontab /home/bbs/crontab
RUN crontab /home/bbs/crontab

USER root
# Notice, in here, mbbsd started service and PROVIDE BIG5 encoding for users.
CMD ["sh","-c","service crond start && while true; do sleep 10; done"]
